apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-rights-panel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tenshi-lab-kube/authentik-rights-panel.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik-rights-panel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
